# Generated by Django 4.2 on 2023-04-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MYBLOGAPP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('Designation', models.CharField(max_length=50)),
                ('create_date', models.DateTimeField()),
            ],
        ),
    ]
